#Blacklisted Items - add the name of the item to blacklist, modid:item_name format, separated with comma.
#Example: "curios:amulet", "curios:ring".
forbiddenTrinkets = []
#Whitelisted Items - add the name of the item to whitelist, modid:item_name format, separated with comma.
#Example: "curios:amulet", "curios:ring".
allowedTrinkets = []
#Set to true to enable dark mode in the mod's GUI screen
enableDarkMode = false
