version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "CHECK"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
everycomp = true
farmersdelight = true
fastitemframes = true
mcwfences = true
enderio = true
mob_grinding_utils = true
projectred_core = true
simplemagnets = true
cookingforblockheads = true
storagedrawers = true
laserbridges = true
redstonepen = true
mcwstairs = true
copycats = true
advanced_ae = true
allthemodium = true
extradisks = true
integratedterminals = true
domum_ornamentum = true
comforts = true
irons_jewelry = true
allthecompressed = true
alltheores = true
morered = true
the_bumblezone = true
ftbquests = true
functionalstorage = true
chisel = true
bobberdetector = true
rftoolsstorage = true
endersdelight = true
dyenamics = true
cccbridge = true
apotheosis = true
create_confectionery = true
deeperdarker = true
culturaldelights = true
rftoolsbase = true
create = true
yungscavebiomes = true
buildinggadgets2 = true
advancedperipherals = true
sfm = true
visualworkbench = true
animal_feeding_trough = true
refinedstorage_mekanism_integration = true
mcwfurnitures = true
create_jetpack = true
refinedstorage = true
cb_multipart = true
sophisticatedstorage = true
xnet = true
aquaculturedelight = true
sliceanddice = true
waystones = true
apothic_enchanting = true
dyenamicsandfriends = true
classicperipherals = true
toms_storage = true
pipez = true
pickletweaks = true
disenchanting_table = true
luminax = true
framedblocks = true
megacells = true
xycraft_machines = true
integratedscripting = true
hostilenetworks = true
another_furniture = true
youkaishomecoming = true
irons_spellbooks = true
dndecor = true
integratedrest = true
create_sa = true
mcwlights = true
growthacceleratortiers = true
mcwholidays = true
globalxp = true
mcwdoors = true
factory_blocks = true
little_big_redstone = true
nomowanderer = true
cabletiers = true
mekanism = true
arsdelight = true
gravestone = true
utilitarian = true
crystalix = true
trashcans = true
create_dragons_plus = true
merequester = true
tesseract = true
ars_additions = true
cobblegengalore = true
industrialization_overdrive = true
ratatouille = true
ae2 = true
platforms = true
ars_nouveau = true
monolib = true
oritech = true
mekmm = true
azurelib = true
fluxnetworks = true
generatorgalore = true
flatcoloredblocks = true
integratedtunnels = true
arseng = true
laserio = true
friendsandfoes = true
uppers = true
quarryplus = true
actuallyadditions = true
projectred_fabrication = true
powah = true
ars_technica = true
mcwbridges = true
entangled = true
mynethersdelight = true
handcrafted = true
rechiseledcreate = true
modern_industrialization = true
ars_creo = true
twilightdelight = true
dndesires = true
create_compressed = true
rftoolsutility = true
supplementaries = true
industrialforegoing = true
minecraft = true
ancientreforging = true
rftoolsbuilder = true
undergarden = true
mowziesmobs = true
create_connected = true
trading_floor = true
xtonesreworked = true
createappliedkinetics = true
createaddition = true
twilightforest = true
ironfurnaces = true
createframed = true
rftoolspower = true
enderstorage = true
creeperoverhaul = true
tradingpost = true
rangedpumps = true
industrialforegoingsouls = true
charginggadgets = true
bigreactors = true
interdimensionalwirelesstransmitter = true
create_aquatic_ambitions = true
illagerinvasion = true
integratedcrafting = true
mcwroofs = true
itemcollectors = true
barteringstation = true
mcwwindows = true
storagedelight = true
brewinandchewin = true
connectedglass = true
cataclysm = true
starbunclemania = true
diagonalwalls = true
expandedae = true
create_enchantment_industry = true
farmingforblockheads = true
mcwpaths = true
simplylight = true
xycraft_world = true
mcwtrpdoors = true
fastpaintings = true
bellsandwhistles = true
mekanismgenerators = true
amendments = true
buzzier_bees = true
extended_industrialization = true
diagonalfences = true
appflux = true
relics = true
sophisticatedbackpacks = true
integrateddynamics = true
morevillagers = true
torchmaster = true
incubation = true
suppsquared = true
chipped = true
sawmill = true
createcasing = true
aquaculture = true
justdirethings = true
terrainslabs = true
modularrouters = true
lootr = true
elevatorid = true
betterarcheology = true
create_things_and_misc = true
endermanoverhaul = true
ars_elemental = true
tempad = true
moderndynamics = true
computercraft = true
sauce = true
reliquary = true
extendedae = true
rechiseled = true
